### ISSUE TITLE
A me non va

### ISSUE THREAD

**Issue by LucaRastrelli** [Yurand2000/Lab4-DockerCompose#2]
mi dà errore 404 not found

**Comment by Yurand2000** [comment]
Guarda il README aggiornato e fammi sapere.

P.S. : Mi devo scusare perche' ho provato a installare Docker su WSL, sorprendentemente si puo' fare e funziona forse anche meglio che installarlo su Windows.

**Comment by LucaRastrelli** [comment]
Aaaaah, mi ero dimenticato nell'URL la parte "/math/". Ora va tutto ^^

Per il discorso WSL, non ho più provato, ho visto che installando docker desktop su windows, ti permette direttamente di farlo comunicare con la distro senza problemi.

**Comment by Yurand2000** [comment]
Sulla WSL ho seguito questo tutorial e non mi ha dato nessun problema. https://dev.to/luckierdodge/how-to-install-and-use-docker-in-wsl2-217l
